-- 创建普通索引
CREATE TABLE test4(
id TINYINT UNSIGNED,
username VARCHAR(20),
INDEX in_id(id),
KEY in_username(username)
);

SHOW CREATE TABLE test4;

-- 创建唯一索引
CREATE TABLE test5(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
username VARCHAR(20) NOT NULL UNIQUE,
card CHAR(18) NOT NULL,
UNIQUE KEY uni_card(card)
);
SHOW CREATE TABLE test5;

-- 创建全文索引
CREATE TABLE test6(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
username VARCHAR(20) NOT NULL UNIQUE,
userDesc VARCHAR(200) NOT NULL,
FULLTEXT INDEX full_userDesc(userDesc)
);
SHOW CREATE TABLE test6;

-- 创建单列索引
CREATE TABLE test7(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
test VARCHAR(20) NOT NULL,
test1 VARCHAR(20) NOT NULL,
test2 VARCHAR(20) NOT NULL,
test3 VARCHAR(20) NOT NULL,
test4 VARCHAR(20) NOT NULL,
INDEX in_test(test)
);
SHOW CREATE TABLE test7;


-- 创建多列索引
CREATE TABLE test8(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
test VARCHAR(20) NOT NULL,
test1 VARCHAR(20) NOT NULL,
test2 VARCHAR(20) NOT NULL,
test3 VARCHAR(20) NOT NULL,
test4 VARCHAR(20) NOT NULL,
INDEX mul_t1_t2_t3(test1,test2,test3)
);
SHOW CREATE TABLE test8;


CREATE TABLE test9(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
test VARCHAR(20) NOT NULL,
test1 VARCHAR(20) NOT NULL,
test2 VARCHAR(20) NOT NULL,
test3 VARCHAR(20) NOT NULL,
test4 VARCHAR(20) NOT NULL,
UNIQUE KEY mul_t1_t2_t3(test1,test2,test3)
);
SHOW CREATE TABLE test9;

DROP INDEX in_id ON test4;
SHOW CREATE TABLE test4;
DROP INDEX in_username ON test4;

CREATE INDEX in_id ON test4(id);
SHOW CREATE TABLE test4;


